### ISSUE TITLE
feat: Labeled Tuple 是 typescript 4.0 才引入的特性，建议少用

### ISSUE THREAD

**Issue by arniu** [innocces/taro-hooks#14]
### Description

[Labeled Tuple Elements] 是 TypeScript 4.0 才引入的新特性，老版本没法用，建议少用。

### Solution

建议少用 [Labeled Tuple Elements]，改用 [Const Assertions]，既方便，兼容性又好。

[Const Assertions]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions
[Labeled Tuple Elements]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements

**Comment by innocces** [comment]
_(:з」∠)_  在下一次版本改动的时候会重新设计现有的类型体系。mark在下一个版本
