### ISSUE TITLE
bug: useRequest 设置debounceInterval,报 Cannot read property 'now' of undefined

### ISSUE THREAD

**Issue by Apigflying** [innocces/taro-hooks#15]
# 使用useRequest 时,在小程序里,会报Cannot read property 'now' of undefined 的错误

- taro-hooks: latest
- taro: 3.3.10
- node: 14.13.0

### 复现步骤
在使用useRequest,并且使用了debounceInterval,会报上述错误
查看源代码 是 p.Date.now 报错,应该是 ahook的问题,我单独使用ahook里的防抖和节流函数也会报这个错误

**Comment by innocces** [comment]
可以提供一下代码片段嘛？ 目前在官网示例中是有debounceInterval的示例的。

**Comment by innocces** [comment]
=。-  `lodash.debounce`的锅。在小程序中拿不到`global`导致`self.Date.now()`报错了。晚上发一个修复版本修复一下这个问题。

 https://github.com/lodash/lodash/blob/2da024c3b4f9947a48517639de7560457cd4ec6c/.internal/root.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L11

**Comment by Apigflying** [comment]
> =。- `lodash.debounce`的锅。在小程序中拿不到`global`导致`self.Date.now()`报错了。晚上发一个修复版本修复一下这个问题。
> 
> https://github.com/lodash/lodash/blob/master/.internal/root.js#L11

ahooks 里的useDebounce 和 useThrottle 也都有这个问题
不知道之后会不会在taro-hooks 里加这两个hook

**Comment by innocces** [comment]
> > =。- `lodash.debounce`的锅。在小程序中拿不到`global`导致`self.Date.now()`报错了。晚上发一个修复版本修复一下这个问题。
> > https://github.com/lodash/lodash/blob/master/.internal/root.js#L11
> 
> ahooks 里的useDebounce 和 useThrottle 也都有这个问题 不知道之后会不会在taro-hooks 里加这两个hook

后面会开启2.0的RFCS. 可以在里面写一下期望有的hooks. 按照顺序会慢慢的都更新进来。但是和环境无关的hooks基本不会重复造轮子。

**Comment by innocces** [comment]
fixed in [v1.5.1](https://github.com/innocces/taro-hooks/releases/tag/taro-hooks-v1.5.1)
