### ISSUE TITLE
请问useRequest是否没有办法做统一的请求/响应拦截?

### ISSUE THREAD

**Issue by ihwf** [innocces/taro-hooks#16]
### useRequest是否没有办法做统一的请求/响应拦截? 

有没有办法实现类似 axios 的 interceptors ? 实现统一在请求前进行参数的修改或者请求后的错误处理?

**Comment by innocces** [comment]
`useRequest`在在未自定义`service`的情况下是直接使用`Taro.request`的。所以可以直接使用[`taro`提供的拦截器](https://taro-docs.jd.com/taro/docs/apis/network/request/addInterceptor)。或者[自定义`service`](https://taro-hooks-innocces.vercel.app/hooks/network/use-request#%E9%9B%86%E6%88%90%E8%AF%B7%E6%B1%82%E5%BA%93): 就可以完全自定义当前请求实例的行为了。
