### ISSUE TITLE
【Bug】: useImage 

### ISSUE THREAD

**Issue by jianhao2010303** [innocces/taro-hooks#20]
### 版本

- taro-hooks:
- taro: 3.3.4
- node:  16
- npm: 8.1.2 
- OS: 微信小程序
- Browser: 

### 复现步骤

问题： 小程序中使用，打开页面直接报错。

定位：在useImage 中应用了BLOB属性。

### 你期望的现象？

不报错。

### 现有的现象？

报错。

**Comment by innocces** [comment]
可以提供一些复现的代码么？ 在代码中是对代码隔离的。只有非小程序端才会使用blob的

**Comment by jianhao2010303** [comment]
![微信图片_20220321115946](https://user-images.githubusercontent.com/22093101/159203667-e7a3ce15-33a3-4506-af81-4a7038780cc0.jpg)

**Comment by jianhao2010303** [comment]
麻烦修复下哈。这个错误导致很多页面无法显示。

**Comment by innocces** [comment]
> 麻烦修复下哈。这个错误导致很多页面无法显示。

可以提供一下复现代码么？
还是直接使用 `useImage`没有其他代码直接就会报错？

**Comment by Przeblysk** [comment]
<img width="413" alt="CleanShot 2022-03-21 at 14 33 50@2x" src="https://user-images.githubusercontent.com/18001272/159214545-3122fb2b-caaa-4a93-90f2-8ae6cb81e0e8.png">
在编译后android机型有问题

**Comment by innocces** [comment]
> <img alt="CleanShot 2022-03-21 at 14 33 50@2x" width="413" src="https://user-images.githubusercontent.com/18001272/159214545-3122fb2b-caaa-4a93-90f2-8ae6cb81e0e8.png">
> 
> 在编译后android机型有问题

可以具体描述一下问题现象么？

**Comment by innocces** [comment]
原因是shims的`compress`中用到的`compressorjs`中[`JavaScript-Canvas-to-Blob`](https://github.com/blueimp/JavaScript-Canvas-to-Blob/blob/master/js/canvas-to-blob.js#L96) 的问题

**Comment by innocces** [comment]
resolve in [1.5.4](https://github.com/innocces/taro-hooks/releases/tag/taro-hooks-v1.5.4)
