### ISSUE TITLE
bug: useClipboardData不支持\r\n

### ISSUE THREAD

**Issue by jianhao2010303** [innocces/taro-hooks#21]
### 版本

- taro-hooks: 1.5.6
- taro: 3.4.7
- node:
- npm:
- OS:
- Browser: chrome 100

### 你期望的现象？

原原生taro方法一致

### 现有的现象？

被当做json串处理了。

**Comment by innocces** [comment]
fix in [taro-hooks-v1.5.7](https://github.com/innocces/taro-hooks/releases/tag/taro-hooks-v1.5.7)
