### ISSUE TITLE
useRequest 不能配置错误重试吗？

### ISSUE THREAD

**Issue by xiao252** [innocces/taro-hooks#23]
例如ahooks useRequest  的 retryCount

- taro-hooks: 1.5.6
- taro:3.4.6
- node:16.0.0
- Browser: chrome99

**Comment by innocces** [comment]
retryCount 是 3.x ahooks 的新增功能. taro-hooks 中的 useRequest 是基于 2.x 的 ahooks 改写的. 目前还不支持

**Comment by innocces** [comment]
可以尝试使用新版本.  2.0版本更新ahooks至3x. 已经可以使用retry了  [传送门](https://next-version-taro-hooks.vercel.app/site/hooks/useRequest/retry)
