### ISSUE TITLE
taro-hooks 下载下来后发现里面并没有usePullDownRefresh这个包

### ISSUE THREAD

**Issue by yangjianmingxc** [innocces/taro-hooks#30]
taro-hooks 下载下来后发现里面并没有usePullDownRefresh这个包，然后我把taro更新到最新的3.4.x重新下载了taro-hooks发现的lib里面
还是没usePullDownRefresh这个包 是bug还是说我的问题

**Comment by innocces** [comment]
这个我稍后看一下回复你

**Comment by innocces** [comment]
**taro-hooks**提供的是**useManualPullDownRefresh**.
你提到的**usePullDownRefresh**是官方提供的，需要从**tarojs/taro**中引入。文档中有详细的说明。记得要仔细阅读文档哦
[传送门](https://taro-hooks-innocces.vercel.app/hooks/layout/use-manual-pull-down-refresh)

**Comment by yangjianmingxc** [comment]
可能我被taro-hooks构建的项目误导 里面有一个这样的引用import { useNavigationBar } from 'taro-hooks'，然后我以为usePullDownRefresh也可以在taro-hooks引用

后来在import {usePullDownRefresh } from ***@***.***/taro'引用是可以了，（可以更新下微信群二维码么，我想加下taro-hooks群）



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "innocces/taro-hooks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月20日(星期三) 上午10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [innocces/taro-hooks] taro-hooks 下载下来后发现里面并没有usePullDownRefresh这个包 (Issue #30)





 
这个我稍后看一下回复你

**Comment by innocces** [comment]
> 可能我被taro-hooks构建的项目误导 里面有一个这样的引用import { useNavigationBar } from 'taro-hooks'，然后我以为usePullDownRefresh也可以在taro-hooks引用 后来在import {usePullDownRefresh } from ***@***.***/taro'引用是可以了，（可以更新下微信群二维码么，我想加下taro-hooks群）
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "innocces/taro-hooks" ***@***.***&gt;; 发送时间:&nbsp;2022年7月20日(星期三) 上午10:34 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [innocces/taro-hooks] taro-hooks 下载下来后发现里面并没有usePullDownRefresh这个包 (Issue #30) 这个我稍后看一下回复你 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

[更新了](https://github.com/innocces/taro-hooks/issues/12#issuecomment-1189761552)
