### ISSUE TITLE
为什么useEnv中的setEnv要在useEffect中触发？

### ISSUE THREAD

**Issue by peterczg** [innocces/taro-hooks#31]
### Question
理论上来说TARO_ENV 在运行的时候就已经确定了环境，但是看useEnv源码的setter却是在useEffect中触发，是否有什么特殊的case要处理，需要这么做？

如果确定是不可变的，那么用useRef来存性能会更好，一些情况下可以少触发一次render。

```ts
function useEnv(): ENV {
  return useRef(getEnv()).current
}
```

**Comment by innocces** [comment]
确实是的。下个版本的这种固定信息类的接口会直接产出。可以等待一下下个版本。

**Comment by peterczg** [comment]
那改的东西不少，我看很多hooks里面都依赖了useEnv

**Comment by innocces** [comment]
> 

因为之前跨端都是用**env**来判断的. 下个版本会走file的模式. **xxx.${env}.ts**. 这样会减少大部分的**env**使用

**Comment by peterczg** [comment]
这里要注意⚠️一个问题，就是支持扩展的编译平台，Taro已经支持的几种平台可以走`xxx.${env}.ts`条件编译，但是第三方自己fork的编译平台，建议留个`xxx.ts`作为兜底，还是拿getEnv()的值。举个不恰当的例子，比如说鸿蒙，Taro还没发布正式版，就可以走兜底的逻辑，让用户可以正常使用，不至于报错。

**Comment by innocces** [comment]
=。-  只要是不带平台后缀的最后都会兜底会**xx.ts**. 不过这次更新要限制**taro.version >= 330**了

**Comment by innocces** [comment]
[进群来讨论吧](https://github.com/innocces/taro-hooks/issues/12#issuecomment-1189761552)

**Comment by innocces** [comment]
新版本已经发布. 暂未宣发. 可以开始尝鲜了 [传送门](https://next-version-taro-hooks.vercel.app)
