### ISSUE TITLE
bug:useRequest 设置  cachekey 以后列表数据残留

### ISSUE THREAD

**Issue by ziqiya** [innocces/taro-hooks#36]
### 版本

- taro-hooks:1.5.8
- taro:3.4.12
- node:14.18.1
- npm:6.14.15
- OS:mac
- Browser:微信小程序

### 复现步骤 
先查询全部列表，下滑请求到第二页数据A，此时再更改查询条件B，这时候发现第二页的数据A没有被清空（这个数据A不是查询条件B应该获得的）

### 你期望的现象？
更改查询条件B以后，应该要把原来请求参数的后面页数数据全部清空

### 现有的现象？
上次查询结果的后面页数的数据残留

### 复现 repo(最好可以提供一个复现的 repo)
https://github.com/ziqiya/taro-hooks-cache-reproduce

**Comment by ziqiya** [comment]
复现仓库 repo 已提供，另外还发现了两个 bug，详见仓库 readMe ，希望可以尽快解决 : )

**Comment by innocces** [comment]
关于三个bug我针对的解释一下:

1.  条件变更。且非首页数据未变化。
2.  滑动无法重新加载
-----
以上的两个问题是因为写法的原因. 
- 原写法
  ```tsx
  /** 商品列表 */
  const {
    data,
    loading,
    reload,
    loadingMore,
    noMore,
    run: fetchList
  } = useRequest(
    (d: any) => {
      const params: any = {
        page: d ? d.page + 1 : 1,
        pageSize: 10,
        filterKey: d?.filterKey || INITIAL_KEY,
      }
      return mockRequest(params)
    },
    {
      loadMore: true,
      ref: scrollViewRef,
      cacheKey: 'id',
      isNoMore: (d: Page) => (d ? d.list.length >= d.total : false)
    }
  )

  const { list } = data || {}

  /** 点击 Tag 选择当前筛选条件 */
  const handleTagClick = (key: string) => {
    fetchList({ filterKey: key, page: INITIAL_PAGE });
    setActiveKey(key)
  }
  ```
  这样的写法会使得**useRequest**内部认为还在维护同一个列表,  因为没有依赖的变更, 关于**activeKey**是业务层面的. 而且你这边用参数的形式传进去了. 内部是不会去解析的
- 推荐写法(且可解决以上两个问题)
  ```tsx
  /** 商品列表 */
  const {
    data,
    loading,
    reload,
    loadingMore,
    noMore,
    run: fetchList
  } = useRequest(
    (d: any) => {
      const params: any = {
        page: d ? d.page + 1 : 1,
        pageSize: 10,
  +   filterKey: activeKey || INITIAL_KEY
      }
      return mockRequest(params)
    },
    {
      loadMore: true,
      ref: scrollViewRef,
      cacheKey: 'id',
      isNoMore: (d: Page) => (d ? d.list.length >= d.total : false),
  +  refreshDeps: [activeKey]
    }
  )

  const { list } = data || {}

  /** 点击 Tag 选择当前筛选条件 */
  const handleTagClick = (key: string) => {
    setActiveKey(key);
  };
  ```
  利用[**refreshDeps**](https://taro-hooks-innocces.vercel.app/hooks/network/use-request#%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E-3)进行数据刷新. 
  
  ![image](https://user-images.githubusercontent.com/38065966/191491601-65fc3c74-aeb0-4840-8726-bf8e84b6352f.png)

-----

3. 视图不满足一页不进行默认加载
   填充视图的行为需要使用者来自行进行业务逻辑增加. 在**useRequest**内部需要通过监听滚动或者是手动调用**loadMore**.
