### ISSUE TITLE
taro-cli创建项目时选择taro-hooks@canary模板，在微信开发者工具控制台报错，渲染失败

### ISSUE THREAD

**Issue by fanhaoyang94** [innocces/taro-hooks#37]
### 相关平台版本

**预览工具：微信开发者工具 Stable 1.06.2210310**
**调试基础库：2.27.2**
**试用框架：React**

### 复现步骤
```
  $ npx @tarojs/cli init taro-hooks-app

  ? 请输入项目介绍 Introduce
  ? 请选择框架 React
  ? 是否需要使用 TypeScript ？ No
  ? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
  ? 请选择编译工具 Webpack5
  ? 请选择包管理工具 yarn
  ? 请选择模板源 Github（最新）
  √ 拉取远程模板仓库成功！
  ? 请选择模板 taro-hooks@canary（使用 taro-hooks canary 版本的模板）

  $ cd  taro-hooks-app && yarn run dev:weapp

  # 打开微信开发者工具导入对应项目，等待编译控制台出现error提醒
```

### 期望结果
微信开发者工具正常预览小程序

### 实际结果
微信开发者工具预览界面白屏，控制台提示error，hook函数执行报错

### 环境信息
```
👽 Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1
      Yarn: 1.22.19
      npm: 8.11.0
```

**Comment by innocces** [comment]
3.5 中 小程序端runtime未正确加载. 需要排查一下

**Comment by awefeng** [comment]
这个问题还是没有修复 ._node_modules_.pnpm_react-reconciler@0.27.0_react@18.0.0_node_modules_react-reconciler_cjs_react-reconciler.production.min.js:98 TypeError: (0 , taro_1.useTaroRef) is not a function

**Comment by innocces** [comment]
> 这个问题还是没有修复 ._node_modules_.pnpm_react-reconciler@[0.27.0_react@18.0.0_node_modules_react-reconciler_cjs_react-reconciler.production.min.js](mailto:0.27.0_react@18.0.0_node_modules_react-reconciler_cjs_react-reconciler.production.min.js):98 TypeError: (0 , taro_1.useTaroRef) is not a function

忙了很长时间。一直没完成新的pr.  可以关注这个的进度 #44

**Comment by innocces** [comment]
#44 

请使用新版重新尝试
