### ISSUE TITLE
bug: useRequest 未触底 连续执行loadmore

### ISSUE THREAD

**Issue by ChenLiheng** [innocces/taro-hooks#39]
### 版本

- taro-hooks: 1.5.9
- taro: 3.5.4
- node: v16.13.0
- npm: 8.1.0
- OS:
- Browser: 

### 你期望的现象？
`ScrollView` 触发 `onScrollToLower`时再执行
### 现有的现象？
https://user-images.githubusercontent.com/11307828/209105033-6c4006cc-339f-4645-bc03-ab70e2fb43bd.mov

### 复现 repo(最好可以提供一个复现的 repo)
见以下最小复现demo
https://github.com/ChenLiheng/useRequestDemo

**Comment by innocces** [comment]
fix #40
