### ISSUE TITLE
bug: 2.0版本useRequest类型定义有问题

### ISSUE THREAD

**Issue by victorWuxz** [innocces/taro-hooks#43]
### 版本

- taro-hooks: 2.0
- taro: 3.2
- node: 16
- npm: 8
- OS: mac
- Browser:

### 复现步骤
引入就报错
### 你期望的现象？
类型提示正确

### 现有的现象？
![image](https://user-images.githubusercontent.com/36194121/227519955-c7d2d59b-f750-418f-8469-5675275b741a.png)

**Comment by innocces** [comment]
=。-  这边长时间没有提供repo. 暂时关闭了.  可以参考[最小示例](https://github.com/innocces/taro-hooks/tree/next/examples/taro-hooks-plugin/src/pages/network/useRequest/basic)查看一下是否写法上有问题. 若依然有问题请附上复现repo重新打开即可

**Comment by parox2014** [comment]
> =。- 这边长时间没有提供repo. 暂时关闭了. 可以参考[最小示例](https://github.com/innocces/taro-hooks/tree/next/examples/taro-hooks-plugin/src/pages/network/useRequest/basic)查看一下是否写法上有问题. 若依然有问题请附上复现repo重新打开即可

你的类型定义确实有问题，在vue中使用时，你返回的本身是一个Ref,但是类型定义是一个Object,实际使用时，要加一个value属性:
```
const req=useRequest();
req.value.loading
req.value.run()
```

**Comment by innocces** [comment]
> > =。- 这边长时间没有提供repo. 暂时关闭了. 可以参考[最小示例](https://github.com/innocces/taro-hooks/tree/next/examples/taro-hooks-plugin/src/pages/network/useRequest/basic)查看一下是否写法上有问题. 若依然有问题请附上复现repo重新打开即可
> 
> 你的类型定义确实有问题，在vue中使用时，你返回的本身是一个Ref,但是类型定义是一个Object,实际使用时，要加一个value属性:
> 
> ```
> const req=useRequest();
> req.value.loading
> req.value.run()
> ```

这个确实是不支持解构的. 为了保持响应式 vue 的版本这里吞吐的是一个 Ref. 所以在所有的示例中产出的结果我们也是直接在 template 中使用的. 避免了多次书写 .value

**Comment by parox2014** [comment]
> > > =。- 这边长时间没有提供repo. 暂时关闭了. 可以参考[最小示例](https://github.com/innocces/taro-hooks/tree/next/examples/taro-hooks-plugin/src/pages/network/useRequest/basic)查看一下是否写法上有问题. 若依然有问题请附上复现repo重新打开即可
> > 
> > 
> > 你的类型定义确实有问题，在vue中使用时，你返回的本身是一个Ref,但是类型定义是一个Object,实际使用时，要加一个value属性:
> > ```
> > const req=useRequest();
> > req.value.loading
> > req.value.run()
> > ```
> 
> 这个确实是不支持解构的. 为了保持响应式 vue 的版本这里吞吐的是一个 Ref. 所以在所有的示例中产出的结果我们也是直接在 template 中使用的. 避免了多次书写 .value

但在实际项目中，不可能只在template中使用的，比如一个简单的场景，需要在useDidShow里面刷新数据，或者任何一个需要主动刷新数据的场景
