### ISSUE TITLE
安装taro-hooks后  ts报错“View”不能用作 JSX 组件。

### ISSUE THREAD

**Issue by pangxzi** [innocces/taro-hooks#45]
![image](https://github.com/innocces/taro-hooks/assets/52907799/471711cf-d3d6-4985-b981-c40cfa677270)
![image](https://github.com/innocces/taro-hooks/assets/52907799/d18c7dd6-5c14-4218-8607-e325fbc73815)

**Comment by innocces** [comment]
这个是因为 taro-hooks 的新版本在 optionalDeps 里添加了 vue 相关的依赖牵扯了 taro 的一个类型文件失常问题

**Comment by innocces** [comment]
新版已移除 `vue` 相关的 `deps`.  若再有问题可再次打开  [taro-hooks@2.0.3](https://github.com/innocces/taro-hooks/releases/tag/taro-hooks%402.0.3)
