### ISSUE TITLE
官网taro init 的taro hooks模板项目启动报错。

### ISSUE THREAD

**Issue by guwan** [innocces/taro-hooks#46]
### 版本

- taro-hooks:latest
- taro:3.6.8
- node:v16.18.1
- npm:9.6.2
- OS: windows10
- Browser: edge

### 复现步骤
yarn dev:h5
### 你期望的现象？
正常启动
### 现有的现象？
报错
### 复现 repo(最好可以提供一个复现的 repo)
https://github.com/guwan/taro-hooks-bug-report.git

按 https://github.com/innocces/taro-hooks/tree/next#-quick-start 改了两处。
yarn add @taro-hooks/plugin-react

plugins: ['@taro-hooks/plugin-react']

没啥用。

**Comment by innocces** [comment]
`1x` 模版里的写法不正确. 因为 `2x` 大部分的 hooks 写法变了. 将 `pages/index/index.(j|t)sx` 替换一下内容:

```jsx
const env = useEnv();
  const { setTitle } = useNavigationBar({ title: "Taro Hooks" });
  const showModal = useModal({
    title: "Taro Hooks Canary!",
    showCancel: false,
    confirmColor: "#8c2de9",
    confirmText: "支持一下"
  });
  const { show } = useToast({ mask: true });

  const handleModal = useCallback(() => {
    showModal({ content: "不如给一个star⭐️!" }).then(() => {
      show({ title: "点击了支持!" });
    });
  }, [show, showModal]);
```

**Comment by inex6** [comment]
hook用不了啊，铁子们 你们怎么办的喃

**Comment by guwan** [comment]
> hook用不了啊，铁子们 你们怎么办的喃

我是降级taro-hooks了，现在可以正常使用，taro-hooks2.0版，现在我用起来问题挺多。
我的是："taro-hooks": "1.5.10",

**Comment by innocces** [comment]
> hook用不了啊，铁子们 你们怎么办的喃

2.0 需要参考官网更新配置和版本.  可以看下配置么

**Comment by innocces** [comment]
> > hook用不了啊，铁子们 你们怎么办的喃
> 
> 我是降级taro-hooks了，现在可以正常使用，taro-hooks2.0版，现在我用起来问题挺多。 我的是："taro-hooks": "1.5.10",

具体问题可以说一下嘛

**Comment by innocces** [comment]
> hook用不了啊，铁子们 你们怎么办的喃

2x 也要参考上面说到的修改方式改一下示例里的写法. 因为很多hooks已经重构了写法

**Comment by guwan** [comment]
> > > hook用不了啊，铁子们 你们怎么办的喃
> > 
> > 
> > 我是降级taro-hooks了，现在可以正常使用，taro-hooks2.0版，现在我用起来问题挺多。 我的是："taro-hooks": "1.5.10",
> 
> 具体问题可以说一下嘛

上次使用的是taro-hooks 2.0.2
1、使用taro自带的taro init 生成一个taro-hook项目，会出现找不到taro-hook/core。
2、按上面改了之后也无法打包成native。找不到taro-hook/core
改没改都提示：
3、 'View' cannot be used as a JSX component.   Its element type 'string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | Iterable<ReactNode> | Component<...> | null | undefined' is not a valid JSX element.     Type 'undefined' is not assignable to type 'Element | ElementClass | null'.

第三点在我上面贴出来的复现项目中可以复现。我刚拉出来，在idea中，还是会报这个错。

**Comment by innocces** [comment]
> > > > hook用不了啊，铁子们 你们怎么办的喃
> > > 
> > > 
> > > 我是降级taro-hooks了，现在可以正常使用，taro-hooks2.0版，现在我用起来问题挺多。 我的是："taro-hooks": "1.5.10",
> > 
> > 
> > 具体问题可以说一下嘛
> 
> 上次使用的是taro-hooks 2.0.2 1、使用taro自带的taro init 生成一个taro-hook项目，会出现找不到taro-hook/core。 2、按上面改了之后也无法打包成native。找不到taro-hook/core 改没改都提示： 3、 'View' cannot be used as a JSX component.   Its element type 'string | number | boolean | ReactElement<any, string | JSXElementConstructor> | Iterable | Component<...> | null | undefined' is not a valid JSX element.     Type 'undefined' is not assignable to type 'Element | ElementClass | null'.
> 
> 第三点在我上面贴出来的复现项目中可以复现。我刚拉出来，在idea中，还是会报这个错。

第三点升级到2.0.3试试看.两个都升级一下

**Comment by performence** [comment]
> `1x` 模版里的写法不正确. 因为 `2x` 大部分的 hooks 写法变了. 将 `pages/index/index.(j|t)sx` 替换一下内容:
> 
> ```js
> const env = useEnv();
>   const { setTitle } = useNavigationBar({ title: "Taro Hooks" });
>   const showModal = useModal({
>     title: "Taro Hooks Canary!",
>     showCancel: false,
>     confirmColor: "#8c2de9",
>     confirmText: "支持一下"
>   });
>   const { show } = useToast({ mask: true });
> 
>   const handleModal = useCallback(() => {
>     showModal({ content: "不如给一个star⭐️!" }).then(() => {
>       show({ title: "点击了支持!" });
>     });
>   }, [show, showModal]);
> ```

你好，我用的是2.0.0-beta-serro.5版本，启动后报错。
![image](https://github.com/innocces/taro-hooks/assets/56541757/373f6b40-2a80-40bf-85a7-d693af12608b)

**Comment by innocces** [comment]
> > `1x` 模版里的写法不正确. 因为 `2x` 大部分的 hooks 写法变了. 将 `pages/index/index.(j|t)sx` 替换一下内容:
> > ```js
> > const env = useEnv();
> >   const { setTitle } = useNavigationBar({ title: "Taro Hooks" });
> >   const showModal = useModal({
> >     title: "Taro Hooks Canary!",
> >     showCancel: false,
> >     confirmColor: "#8c2de9",
> >     confirmText: "支持一下"
> >   });
> >   const { show } = useToast({ mask: true });
> > 
> >   const handleModal = useCallback(() => {
> >     showModal({ content: "不如给一个star⭐️!" }).then(() => {
> >       show({ title: "点击了支持!" });
> >     });
> >   }, [show, showModal]);
> > ```
> 
> 你好，我用的是2.0.0-beta-serro.5版本，启动后报错。 ![image](https://user-images.githubusercontent.com/56541757/252602938-373f6b40-2a80-40bf-85a7-d693af12608b.png)

请将相关版本都更新至 2.0.3

**Comment by guwan** [comment]
> ```js
> const env = useEnv();
>   const { setTitle } = useNavigationBar({ title: "Taro Hooks" });
>   const showModal = useModal({
>     title: "Taro Hooks Canary!",
>     showCancel: false,
>     confirmColor: "#8c2de9",
>     confirmText: "支持一下"
>   });
>   const { show } = useToast({ mask: true });
> 
>   const handleModal = useCallback(() => {
>     showModal({ content: "不如给一个star⭐️!" }).then(() => {
>       show({ title: "点击了支持!" });
>     });
>   }, [show, showModal]);
> ```

升级到2.0.3问题解决的，谢谢

**Comment by innocces** [comment]
> > ```js
> > const env = useEnv();
> >   const { setTitle } = useNavigationBar({ title: "Taro Hooks" });
> >   const showModal = useModal({
> >     title: "Taro Hooks Canary!",
> >     showCancel: false,
> >     confirmColor: "#8c2de9",
> >     confirmText: "支持一下"
> >   });
> >   const { show } = useToast({ mask: true });
> > 
> >   const handleModal = useCallback(() => {
> >     showModal({ content: "不如给一个star⭐️!" }).then(() => {
> >       show({ title: "点击了支持!" });
> >     });
> >   }, [show, showModal]);
> > ```
> 
> 升级到2.0.3问题解决的，谢谢

那关掉了哦

**Comment by tylerrrkd** [comment]
安装对应插件解决的[@taro-hooks/plugin-react](https://github.com/innocces/taro-hooks)

**Comment by innocces** [comment]
> 安装对应插件解决的[@taro-hooks/plugin-react](https://github.com/innocces/taro-hooks)

=。-  官方模版仓库的pr一直没被合进去

**Comment by tylerrrkd** [comment]
> > 安装对应插件解决的[@taro-hooks/plugin-react](https://github.com/innocces/taro-hooks)
> 
> =。- 官方模版仓库的pr一直没被合进去

阿酱是你吗芜湖

**Comment by innocces** [comment]
> > > 安装对应插件解决的[@taro-hooks/plugin-react](https://github.com/innocces/taro-hooks)
> > 
> > 
> > =。- 官方模版仓库的pr一直没被合进去
> 
> 阿酱是你吗芜湖

突然被逮到

**Comment by Chen-jj** [comment]
> > 安装对应插件解决的[@taro-hooks/plugin-react](https://github.com/innocces/taro-hooks)
> 
> =。- 官方模版仓库的pr一直没被合进去

不好意思，刚注意到，马上处理

**Comment by Tenodec** [comment]
真的蛋疼，换了台机器，自动装最新的taro-hook。就跑不起来了。还得降级

**Comment by innocces** [comment]
> 真的蛋疼，换了台机器，自动装最新的taro-hook。就跑不起来了。还得降级

=。-  之前为了让大家可以直接使用最新版。所以依赖直接写了 latest。这个确实也造成了新版发布造成的问题
