### ISSUE TITLE
feat: preact支持

### ISSUE THREAD

**Issue by LiZhequ** [innocces/taro-hooks#47]
### Description
https://github.com/innocces/taro-hooks/blob/d3b9214662897554dabd013111d196f2f3974f2a/packages/plugin-react/src/index.ts#L6
看了下`plugin-react`的实现，里面没用对preact的判断，导致无法与preact一起使用，能否加上preact的兼容
### Solution
兼容preact

**Comment by innocces** [comment]
我记得官方的 preact 模式其实是在内部用 preact 替换了 react 的alias. 我晚点看下这里具体再 preact 里的判断吧

**Comment by LiZhequ** [comment]
> 我记得官方的 preact 模式其实是在内部用 preact 替换了 react 的alias. 我晚点看下这里具体再 preact 里的判断吧

是这样没错，不过这里的问题是判断了不是react直接return了，没有后续配置@taro-hooks/core的alias导致错误

**Comment by innocces** [comment]
> > 我记得官方的 preact 模式其实是在内部用 preact 替换了 react 的alias. 我晚点看下这里具体再 preact 里的判断吧
> 
> 是这样没错，不过这里的问题是判断了不是react直接return了，没有后续配置@taro-hooks/core的alias导致错误

ok. 晚些我看看

**Comment by innocces** [comment]
官方的 preact 模版是可以正常运行的么

**Comment by innocces** [comment]
=。-  官方的 preact 模版我试了下都初始化后无法运行. 所以没有校验插件的合法性。
你可以用你现有可以跑起来的项目试一下。

#51 
https://github.com/innocces/taro-hooks/blob/3620d3f1b8077f254d2cd0101fb2783eb810e3e5/packages/plugin-react/src/index.ts#L5

**Comment by LiZhequ** [comment]
试了下2.0.4已支持preact
