### ISSUE TITLE
bug: taro-hooks 的依赖是否遗漏了@taro-hooks/core

### ISSUE THREAD

**Issue by Chen-jj** [innocces/taro-hooks#48]
### 版本

同：https://github.com/NervJS/taro/issues/14181

### 复现步骤

`taro-hooks` 依赖了 `@taro-hooks/core`，但是没有将其添加为依赖：

https://github.com/innocces/taro-hooks/blob/d3b9214662897554dabd013111d196f2f3974f2a/packages/hooks/src/createUseInfoHook/index.ts#L1

相关 issues：https://github.com/NervJS/taro/issues/14181

命令行:
taro init taro_hooks

? 请输入项目介绍 taro
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择编译工具 Webpack5
? 请选择包管理工具 npm
? 请选择模板源 Github（最新）
✔ 拉取远程模板仓库成功！
? 请选择模板 taro-hooks（使用 taro-hooks 的模板）

### 你期望的现象？

taro-hooks 模板正常运行

### 现有的现象？

taro-hooks 模板运行失败

**Comment by innocces** [comment]
2x 版本的 core 是一个幽灵依赖。 是通过插件注入的。(@taro-hooks/plugin-xxx)

**Comment by innocces** [comment]
新pr的模版里非  cannay 的已经把版本锁死在1x了.  cannary 的都写了对应框架的插件模版不会有这个问题

**Comment by innocces** [comment]
#46

**Comment by Chen-jj** [comment]
了解~模板 PR 麻烦处理一下哈，更新后我再试试：https://github.com/NervJS/taro-project-templates/pull/105
