### ISSUE TITLE
bug: 微信小程序无法运行

### ISSUE THREAD

**Issue by CloudyBao** [innocces/taro-hooks#50]
### 版本

- taro-hooks:2.0.3
- taro:3.6.10
- node:18.15.0
- npm:9.5.0
- OS:windows 11
- Browser: chorm

### 复现步骤
yarn dev:weapp
### 你期望的现象？
运行成功
### 现有的现象？
运行失败
h5端可以正常运行
> resolve 'react' in 'D:\workplace\taro\hooks-demo\node_modules\@taro-hooks\plugin-react\dist'
>   Parsed request is a module
>   using description file: D:\workplace\taro\hooks-demo\node_modules\@taro-hooks\plugin-react\package.json (relative path: ./dist)
>     aliased with mapping 'react': 'cjs/react.production.min.js' to 'cjs/react.production.min.js'     
>       Parsed request is a module
>       using description file: D:\workplace\taro\hooks-demo\node_modules\@taro-hooks\plugin-react\package.json (relative path: ./dist)
>         Field 'browser' doesn't contain a valid alias configuration
>         resolve as module
>           D:\workplace\taro\hooks-demo\node_modules\@taro-hooks\plugin-react\dist\node_modules doesn't exist or is not a directory
>           looking for modules in D:\workplace\taro\hooks-demo\node_modules\@taro-hooks\plugin-react\node_modules
>             D:\workplace\taro\hooks-demo\node_modules\@taro-hooks\plugin-react\node_modules\cjs doesn't exist
>           D:\workplace\taro\hooks-demo\node_modules\@taro-hooks\node_modules doesn't exist or is not a directory
>           D:\workplace\taro\hooks-demo\node_modules\node_modules doesn't exist or is not a directory 
>           looking for modules in D:\workplace\taro\hooks-demo\node_modules
>             D:\workplace\taro\hooks-demo\node_modules\cjs doesn't exist
>           D:\workplace\taro\node_modules doesn't exist or is not a directory
>           D:\workplace\node_modules doesn't exist or is not a directory
>           D:\node_modules doesn't exist or is not a directory
> 
> → Watching... [2023/7/27 12:05:19]
> 
> node:internal/process/promises:288
>             triggerUncaughtException(err, true /* fromPromise */);
>             ^
> 
> [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
>   code: 'ERR_UNHANDLED_REJECTION'
> }

**Comment by innocces** [comment]
是使用哪个模版创建的？ 2x ？

**Comment by CloudyBao** [comment]
> 是使用哪个模版创建的？ 2x ？

好像是用@什么开头，2x也是这个问题，我刚才又试试了taro 3.6.10内置的模板都有问题，
