### ISSUE TITLE
feat: 支持unplugin-auto-import

### ISSUE THREAD

**Issue by yifengyoujian** [innocces/taro-hooks#52]
### Solution
现在支持unplugin-auto-import吗,  支持以后页面应该除了组件库基本上可以不需要额外的引入

**Comment by innocces** [comment]
emmm~ 因为底层是由 taro 进行构建的。不太清楚官方是否已经支持了。
目前我看了下 unplugin-auto-import 插件官方描述。 似乎只需要在 AutoImport 里描述一下自动引入的包和模块的关系就好了。 我没有亲自尝试。需要试一下是否是支持的。这个看起来不需要库作者来生成什么信息。
是需要库产出一个 metajson 来供插件消费么？

**Comment by yifengyoujian** [comment]
在unplugin-auto-import的提议中看到过taro, 但是被unplugin-auto-import官方驳回了. 可以用户自己配置的只需要编写对应的来源跟api就可以了( 但是手懒( ω ) )

**Comment by innocces** [comment]
那大概输出一个meta就好了。有兴趣可以pr一个呀

**Comment by innocces** [comment]
#53 

https://github.com/innocces/taro-hooks/releases/tag/taro-hooks%402.0.5
