### ISSUE TITLE
bug: 在app.ts里面使用时会报错

### ISSUE THREAD

**Issue by chj-damon** [innocces/taro-hooks#55]
### 版本

- taro-hooks: 2.0.5
- taro: 3.6.13
- node: 16.19.1
- npm:8.19.3
- OS:macOS 13.4.1
- Browser:

### 复现步骤
在下面的复现repo的src/app.tsx里面引入taro-hooks， 控制台就可以看到报错信息。注释掉的话就没问题

### 你期望的现象？
可以在app.ts[x]里面正常使用taro-hooks

### 现有的现象？
使用报错：
![image](https://github.com/innocces/taro-hooks/assets/4902684/2d6dfeaa-2e1e-48e3-85c7-fb1c5c22ed4e)

### 复现 repo(最好可以提供一个复现的 repo)
https://github.com/thundersdata-frontend/taro-style/tree/master/demo

**Comment by innocces** [comment]
请仔细阅读文档  https://next-version-taro-hooks.vercel.app/site/docs/quick/react-useage#%E5%AE%89%E8%A3%85%E6%8F%92%E4%BB%B6
