### ISSUE TITLE
bug: Cannot find module '@taro-hooks/core'

### ISSUE THREAD

**Issue by chj-damon** [innocces/taro-hooks#58]
### 版本

- taro-hooks: 2.0.5
- taro: 3.6.13
- node: 16.19.1
- npm: 8.19.3
- OS: macos
- Browser: 小程序

### 复现步骤
直接用vscode打开项目，在pages/index/index.tsx文件里有一个import from '@taro-hooks/core'的地方，可以看到这里提示说找不到这个模块。但是功能是正常的，只是TS在报错。
我已经检查过，在types/global.d.ts里面已经按照文档引入了对应的类型文件

### 你期望的现象？
TS不报错

### 现有的现象？
TS提示找不到`@taro-hooks/core`这个模块

### 复现 repo(最好可以提供一个复现的 repo)
https://github.com/thundersdata-frontend/taro-style/tree/master/demo

**Comment by innocces** [comment]
添加以下内容即可: 
https://github.com/innocces/taro-hooks/blob/96898f4572612720db8d1ec13b3e0923ddd3bf5e/examples/taro-hooks-plugin/global.d.ts#L3

**Comment by chj-damon** [comment]
@innocces 实测，不需要加这一句，只需要有上面那个`/// <reference types="@taro-hooks/plugin-react" />` 就够了。
我项目之所以失败，是因为d.ts文件放在了types文件夹里，所以在`tsconfig.json`里面include进来就好了。
```tsx
"include": ["src/**/*", "types/*.d.ts"]
```
