### ISSUE TITLE
bug: taro-hooks2.0 不支持rn

### ISSUE THREAD

**Issue by OrrinHatch** [innocces/taro-hooks#60]
### 版本

- taro-hooks: 2.0.6
- taro:  3.6.13
- node: 18.16.0
- npm: 9.5.1
- OS: mac m2 Pro
- Browser: chrome

### 复现步骤
按照官网2.X文档进行安装, @taro-hooks/plugin-react 也安装了
### 复现 repo(最好可以提供一个复现的 repo)
<img width="336" alt="截屏2023-09-21 17 48 20" src="https://github.com/innocces/taro-hooks/assets/99718299/e0a6c45f-2f19-491f-8816-193f4a429d64">

**Comment by innocces** [comment]
emmm~ rn貌似要配置 metirc。 这个mark一下周末看看~~ 
或者有兴趣可以一起看看。其实 @taro-hooks/core 是做了一个软链。rn可能没有被扫到

**Comment by innocces** [comment]
有在 config 里的 plugin 声明  '@taro-hooks/plugin-react' 么？ [配置](https://next-taro-hooks.pages.dev/site/docs/quick/react-useage#%E9%A1%B9%E7%9B%AE%E9%85%8D%E7%BD%AE)

**Comment by innocces** [comment]
如果配置了的话可以把完整的 config/index.js 贴出来看下么

**Comment by OrrinHatch** [comment]
<img width="763" alt="截屏2023-10-07 09 34 12" src="https://github.com/innocces/taro-hooks/assets/99718299/8104fd47-40c1-4bca-98f3-caf8854959c9">

**Comment by innocces** [comment]
是直接用的官方的rn-template创建的项目么？

**Comment by OrrinHatch** [comment]
是的

**Comment by innocces** [comment]
ok ~ mark 一下周末看看. 或者直接在 alias 里加一下:
```js
{
  '@taro-hooks/core': '@taro-hooks/plugin-react/dist/runtime'
}
```

**Comment by innocces** [comment]
似乎看起来动态修改 webpack 的 define 在 rn 这边不会被合并到 metro 的配置中

**Comment by OrrinHatch** [comment]
Taro hooks 2.0 rn端 又爆出找不到TARO_ENV

**Comment by OrrinHatch** [comment]
<img width="357" alt="截屏2023-10-12 18 43 42" src="https://github.com/innocces/taro-hooks/assets/99718299/441b26d8-26db-458e-8fae-7fa11f3ac553">

**Comment by OrrinHatch** [comment]
没办法,我还是降到1.5的版本吧

**Comment by OrrinHatch** [comment]
> ok ~ mark 一下周末看看. 或者直接在 alias 里加一下:
> 
> ```js
> {
>   '@taro-hooks/core': '@taro-hooks/plugin-react/dist/runtime'
> }
> ```

可以解决这个bug

**Comment by innocces** [comment]
所以是已经解决了么？ 还是？

**Comment by OrrinHatch** [comment]
解决了@taro-hooks/core, 又有其他bug

**Comment by innocces** [comment]
那看起来rn确实不能在webpack里面动态插值。这个得好好看看。

**Comment by innocces** [comment]
试试在 config.ts 里的 define 里加一下
```ts
TARO_ENV: JSON.stringify(process.env.TARO_ENV?.toLocaleUpperCase())
```
