### ISSUE TITLE
使用痛点 建议添加或修改

### ISSUE THREAD

**Issue by Hanakisou** [innocces/taro-hooks#61]
- useStorage 添加同步配置
- 添加信息： 当前wifi信息和wifi列表
- useRouter 添加Taro.preload 和 获取preloadData

**Comment by innocces** [comment]
=。-  不如来个 pr

**Comment by innocces** [comment]
storage 目前不会设计同步模式。因为要兼容 rn 侧

**Comment by innocces** [comment]
[usePreload](https://github.com/innocces/taro-hooks/commit/2b3186515dce05071b882310142059df965da583)已经有了。你依然可以使用 useRouter 来使用或直接使用 usePreload

**Comment by innocces** [comment]
wifi 需要设计一下。先 close了。 如果可以的话贡献一个也可以
