### ISSUE TITLE
bug: AutoImport 引入，在vscode里面看不到函数的方法

### ISSUE THREAD

**Issue by oydiligent** [innocces/taro-hooks#62]
### 版本

- taro-hooks: 2.0.7
- taro: 3.6.17
- node: v16.14.0
- npm: 8.3.1
- OS: window
- Browser: 微信小程序及支付宝小程序

### 复现步骤
选择最新taro-hooks@2模板，其次将taro-hooks相关升级成最新2.0.7，@taro-hooks/plugin-auto-import": "^2.0.7",
![image](https://github.com/innocces/taro-hooks/assets/19690319/ad714842-8d60-407c-a0c0-cc2b2610a7d2)

### 你期望的现象？
在vscode中看到引入的方法
### 现有的现象？
![image](https://github.com/innocces/taro-hooks/assets/19690319/d97abafb-dd83-43fa-b656-a6258614a13f)

**Comment by innocces** [comment]
咦。你直接用默认配置不要加自定义配置呢？

**Comment by innocces** [comment]
默认会把 dts 生成到 src 下

**Comment by innocces** [comment]
https://github.com/innocces/taro-hooks/blob/bcc647294cba3061da48d6bb4a7932511542086c/examples/taro-hooks-plugin/tsconfig.json#L28

或者 加一下 include. 因为类型实际上是会默认生成成一个全局声明的类型文件的

**Comment by oydiligent** [comment]
> https://github.com/innocces/taro-hooks/blob/bcc647294cba3061da48d6bb4a7932511542086c/examples/taro-hooks-plugin/tsconfig.json#L28
> 
> 或者 加一下 include. 因为类型实际上是会默认生成成一个全局声明的类型文件的

我用的不是ts版的，没有这个配置，其次默认会把 dts 生成到 src 下，不会生成eslintrc-auto-import.json这个，只有auto-imports.d.ts文件

**Comment by oydiligent** [comment]
好像这个自动导入只支持ts版@~@

**Comment by oydiligent** [comment]
![image](https://github.com/innocces/taro-hooks/assets/19690319/c5c518c0-53fd-4476-80ca-04eec4ce57f4)
还有一个问题，prebundle配置是不是要配置其他的东西，dist生成的文件app.js文件生成的文件引入错误了
![image](https://github.com/innocces/taro-hooks/assets/19690319/427d757d-70bf-4c73-a20b-bc15bf3223e2)

**Comment by innocces** [comment]
> 好像这个自动导入只支持ts版@~@

如果没有 ts 的配置确实是看不到自动导入的方法的类型的

**Comment by innocces** [comment]
> ![image](https://user-images.githubusercontent.com/19690319/274474971-c5c518c0-53fd-4476-80ca-04eec4ce57f4.png) 还有一个问题，prebundle配置是不是要配置其他的东西，dist生成的文件app.js文件生成的文件引入错误了 ![image](https://user-images.githubusercontent.com/19690319/274475198-427d757d-70bf-4c73-a20b-bc15bf3223e2.png)

这个光看这个截图看不出什么真实的错误信息。可以贴一下具体的错误信息么？ 我这边试了下是没什么问题的

**Comment by oydiligent** [comment]
> [<img alt="@oydiligent" width="40" height="40" src="https://avatars.githubusercontent.com/u/19690319?s=80&amp;v=4">](/oydiligent)
> 
> Write Preview
> 
> 
> Attach files by dragging & dropping, selecting or pasting them.[ ](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
>  Close issue
> Comment
> Remember, contributions to this repository should follow its [contributing guidelines](/innocces/taro-hooks/blob/bcc647294cba3061da48d6bb4a7932511542086c/CONTRIBUTING.md).
> Assignees
> No one assigned
> Labels
> [ bug ](/innocces/taro-hooks/labels/bug)
> Projects
> None yet
> Milestone
> No milestone
> Development
> No branches or pull requests
> 
> Notifications
> Customize
> 
> Unsubscribe
> You’re receiving notifications because you authored the thread.
> 
> 2 participants

![image](https://github.com/innocces/taro-hooks/assets/19690319/877c6f8b-632b-4232-aabd-5ec473359631)
这个require是个错的呀，我看别人有的生成的默认是require("./prebundle/vendors-node_modules_taro_weapp_prebundle_react-dom_js.js")，我这个少了一个层级

**Comment by innocces** [comment]
周末我试一下你这个版本吧。目前示例库用的是 3.6.11 是没这个问题的

https://github.com/innocces/taro-hooks/blob/bcc647294cba3061da48d6bb4a7932511542086c/examples/taro-hooks-plugin/package.json#L59

**Comment by innocces** [comment]
似乎看不到方法定义是 un-import 自带的一个问题: [#318](https://github.com/unplugin/unplugin-auto-import/issues/318)

**Comment by innocces** [comment]
> > [<img alt="@oydiligent" width="40" height="40" src="https://avatars.githubusercontent.com/u/19690319?s=80&amp;v=4">](/oydiligent)
> > Write Preview
> > Attach files by dragging & dropping, selecting or pasting them.[ ](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
> > Close issue
> > Comment
> > Remember, contributions to this repository should follow its [contributing guidelines](/innocces/taro-hooks/blob/bcc647294cba3061da48d6bb4a7932511542086c/CONTRIBUTING.md).
> > Assignees
> > No one assigned
> > Labels
> > [ bug ](/innocces/taro-hooks/labels/bug)
> > Projects
> > None yet
> > Milestone
> > No milestone
> > Development
> > No branches or pull requests
> > Notifications
> > Customize
> > Unsubscribe
> > You’re receiving notifications because you authored the thread.
> > 2 participants
> 

![image](https://user-images.githubusercontent.com/19690319/274490513-877c6f8b-632b-4232-aabd-5ec473359631.png) 这个require是个错的呀，我看别人有的生成的默认是require("./prebundle/vendors-node_modules_taro_weapp_prebundle_react-dom_js.js")，我这个少了一个层级
![code](https://github.com/innocces/taro-hooks/assets/38065966/21aee363-3863-4d68-8604-3f77eb1b72ed)

![code](https://github.com/innocces/taro-hooks/assets/38065966/fe27a0e8-5c55-45e2-8644-f81fabfc0ba8)
![code](https://github.com/innocces/taro-hooks/assets/38065966/e23ea817-dfd5-403b-a130-346533f88217)

我试了下3.6.11 版本的 taro-hooks@2 版本加上 autoImport 插件没有复现你这个路径错误的问题。应该是其他配置的问题。

**Comment by yifengyoujian** [comment]
高于3.6.16低于3.6.19会出现这个问题, 官方已经解决了

**Comment by innocces** [comment]
> 高于3.6.16低于3.6.19会出现这个问题, 官方已经解决了

最近比较忙，没有关注。解决了的话就暂时关闭了。如果有相关issue可以link一下。这样有同样问题的小伙伴可以顺着 metion 过去
