### ISSUE TITLE
bug: TypeError: 'getOwnPropertyDescriptor' on proxy: trap reported non-configurability for property 'onLaunch' which is either non-existent or configurable in the proxy target

### ISSUE THREAD

**Issue by zjcrender** [innocces/taro-hooks#63]
### 版本

- taro-hooks: 2.0.7
- taro: 3.6.18
- node: 16.20.2
- npm: 8.19.4
- OS: MacBook Pro  M2 sonoma
- Browser:

### 复现步骤

示例代码：[codesandbox](https://codesandbox.io/p/github/zjcrender/taro-alipay/main?import=true&embed=1&file=%2F.editorconfig&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cloqqv6zr00073b6jbx1ayul8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cloqqv6zr00033b6jr4s9otix%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cloqqv6zr00053b6juyen02dx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cloqqv6zr00063b6j2ylrvtov%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cloqqv6zr00033b6jr4s9otix%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloqqv6zr00023b6j6uskzma1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.editorconfig%2522%257D%255D%252C%2522id%2522%253A%2522cloqqv6zr00033b6jr4s9otix%2522%252C%2522activeTabId%2522%253A%2522cloqqv6zr00023b6j6uskzma1%2522%257D%252C%2522cloqqv6zr00063b6j2ylrvtov%2522%253A%257B%2522id%2522%253A%2522cloqqv6zr00063b6j2ylrvtov%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cloqqv6zr00053b6juyen02dx%2522%253A%257B%2522id%2522%253A%2522cloqqv6zr00053b6juyen02dx%2522%252C%2522activeTabId%2522%253A%2522cloqr0z5500l13b6j18l60wr4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloqqv6zr00043b6j46sdpcb1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cloqqv7g80010eeexdqj83efp%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522cloqqvwu9008d3b6jf3qwofdm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%253Aalipay%2522%252C%2522id%2522%253A%2522cloqr0z5500l13b6j18l60wr4%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

1. `npm install`
2. 确保`project.alipay.json`设置`developOptions.hotReload`为`true`
3. `npm run dev:alipay`
4. 打开支付宝IDE，收到报错信息

### 你期望的现象？
获取到app中的globalData

### 复现 repo(最好可以提供一个复现的 repo)
[repo](https://github.com/zjcrender/taro-alipay)

**Comment by innocces** [comment]
可以贴一下 package.json 和 真实使用处的位置代码片段么

**Comment by zjcrender** [comment]
@innocces 不好意思，忘记提是支付宝小程序了。
代码复现：[codesandbox](https://codesandbox.io/p/github/zjcrender/taro-alipay/main?import=true&embed=1&file=%2F.editorconfig&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cloqqv6zr00073b6jbx1ayul8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cloqqv6zr00033b6jr4s9otix%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cloqqv6zr00053b6juyen02dx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cloqqv6zr00063b6j2ylrvtov%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cloqqv6zr00033b6jr4s9otix%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloqqv6zr00023b6j6uskzma1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.editorconfig%2522%257D%255D%252C%2522id%2522%253A%2522cloqqv6zr00033b6jr4s9otix%2522%252C%2522activeTabId%2522%253A%2522cloqqv6zr00023b6j6uskzma1%2522%257D%252C%2522cloqqv6zr00063b6j2ylrvtov%2522%253A%257B%2522id%2522%253A%2522cloqqv6zr00063b6j2ylrvtov%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cloqqv6zr00053b6juyen02dx%2522%253A%257B%2522id%2522%253A%2522cloqqv6zr00053b6juyen02dx%2522%252C%2522activeTabId%2522%253A%2522cloqr0z5500l13b6j18l60wr4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloqqv6zr00043b6j46sdpcb1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cloqqv7g80010eeexdqj83efp%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522cloqqvwu9008d3b6jf3qwofdm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%253Aalipay%2522%252C%2522id%2522%253A%2522cloqr0z5500l13b6j18l60wr4%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
然后已经发现问题在哪了，`project.alipay.json`设置了`developOptions.hotReload`就会出现这个问题

**Comment by innocces** [comment]
> @innocces 不好意思，忘记提是支付宝小程序了。 代码复现：[codesandbox](https://codesandbox.io/p/github/zjcrender/taro-alipay/main?import=true&embed=1&file=%2F.editorconfig&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cloqqv6zr00073b6jbx1ayul8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cloqqv6zr00033b6jr4s9otix%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cloqqv6zr00053b6juyen02dx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cloqqv6zr00063b6j2ylrvtov%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cloqqv6zr00033b6jr4s9otix%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloqqv6zr00023b6j6uskzma1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.editorconfig%2522%257D%255D%252C%2522id%2522%253A%2522cloqqv6zr00033b6jr4s9otix%2522%252C%2522activeTabId%2522%253A%2522cloqqv6zr00023b6j6uskzma1%2522%257D%252C%2522cloqqv6zr00063b6j2ylrvtov%2522%253A%257B%2522id%2522%253A%2522cloqqv6zr00063b6j2ylrvtov%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cloqqv6zr00053b6juyen02dx%2522%253A%257B%2522id%2522%253A%2522cloqqv6zr00053b6juyen02dx%2522%252C%2522activeTabId%2522%253A%2522cloqr0z5500l13b6j18l60wr4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloqqv6zr00043b6j46sdpcb1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cloqqv7g80010eeexdqj83efp%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522cloqqvwu9008d3b6jf3qwofdm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%253Aalipay%2522%252C%2522id%2522%253A%2522cloqr0z5500l13b6j18l60wr4%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 然后已经发现问题在哪了，`project.alipay.json`设置了`developOptions.hotReload`就会出现这个问题

那已经发现问题的话这边是不是就可以关了。
