### ISSUE TITLE
bug: useRequest with options refreshOnWindowFocus init render two times

### ISSUE THREAD

**Issue by master1lan** [innocces/taro-hooks#64]
### 版本

- taro-hooks:2.0.7
- taro:3.5.8
- node:16.20.0
- npm:yarn v1.22.19
- OS:macos 14
- Browser: chrome或者微信小程序

### 复现步骤
npx @tarojs/cli@3.5.8 init taro-hooks-app
选择taro-hooks模版，添加@taro-hooks/plugin-react依赖。
<img width="676" alt="image" src="https://github.com/innocces/taro-hooks/assets/66736072/322060ef-1341-404b-abf2-de7fdff2bbe1">

index.tsx文件改成这样，

### 你期望的现象？
useRequest提供参数refreshOnWindowFocus后初次渲染仅请求一次。

### 现有的现象？
<img width="663" alt="image" src="https://github.com/innocces/taro-hooks/assets/66736072/56333610-219d-4e18-bcbf-5e81e71b6850">
<img width="406" alt="image" src="https://github.com/innocces/taro-hooks/assets/66736072/391c9163-c362-4569-8c11-c2f2de0d66be">
可以看到不是在严格模式下运行时，仍然请求了两遍。
无论是在h5上面还是小程序上面，都会在初次渲染的时候请求两遍。

**Comment by master1lan** [comment]
不清楚源代码怎么写的，不过感觉可以用一个useRef判断一下是不是初次渲染然后绕过第一次didShow的执行

**Comment by innocces** [comment]
> 不清楚源代码怎么写的，不过感觉可以用一个useRef判断一下是不是初次渲染然后绕过第一次didShow的执行

ʕ •ᴥ•ʔ mark 了，周末看一下

**Comment by innocces** [comment]
fixed in [v2.0.8](https://github.com/innocces/taro-hooks/releases/tag/taro-hooks%402.0.8)
