### ISSUE TITLE
bug: useSystemInfo 返回空对象

### ISSUE THREAD

**Issue by Nick742037091** [innocces/taro-hooks#65]
### 版本

- taro-hooks: 2.0.8
- taro: v3.6.17
- node: v16.19.1
- npm:8.19.3
- OS:macOS
- Browser: Chrome 120.0.6099.109（正式版本） (arm64)

### 复现步骤
const systemInfo = useSystemInfo()

### 你期望的现象？

能正确获取到SystemInfo

### 现有的现象？

SystemInfo为空对象

浏览器Console 输出错误： 🎮[taro-hooks]---[createUseInfoHook]: fn is not a function. undefined

![image](https://github.com/innocces/taro-hooks/assets/20139399/14d87bcb-d19e-4881-9424-1dc53a1ff3af)
看源码，是taro_1["default"].getSystemInfoSync为 undefined导致

### 复现 repo(最好可以提供一个复现的 repo)

const systemInfo = useSystemInfo()
console.log(JSON.stringify((systemInfo)))

**Comment by innocces** [comment]
这个似乎是 taro 的问题. 
[demo](https://next-taro-hooks.pages.dev/react/pages/index/index) 中 taro 版本为 3.6.11 运行状态是正常的
尝试降级或升级 taro 版本试试.

**Comment by innocces** [comment]
目前 demo 已经升级到 3.6.21 了。 应该是你使用的 taro 版本的问题。先暂时关闭了。若有问题可以到 taro 那边开一个  issue

**Comment by Nick742037091** [comment]
> 目前 demo 已经升级到 3.6.21 了。 应该是你使用的 taro 版本的问题。先暂时关闭了。若有问题可以到 taro 那边开一个 issue
升级到v3.6.21没问题了
