### ISSUE TITLE
preloadData这个数据好像未进行写入

### ISSUE THREAD

**Issue by CloudyBao** [innocces/taro-hooks#69]
### Question
我看了包内的源码，好像并未封装preloadData，无论是useRouter内的preloadData还是usePreload,usePreload直接使用的是useRouter的方法，而preloadData没有进行任何操作。无论是route.preloadData还是const [preloadData] = usePreload();preloadData都为空

**Comment by innocces** [comment]
该方法是针对下一个页面的预加载数据、那么应该是在跳转前的页面执行 preload。 然后在跳转后的页面使用 preloadData。因为本质上 preloadData 是在 router 内查看的

**Comment by CloudyBao** [comment]
> 该方法是针对下一个页面的预加载数据、那么应该是在跳转前的页面执行 preload。 然后在跳转后的页面使用 preloadData。因为本质上 preloadData 是在 router 内查看的

对的，实际上的使用是我在上一个页面执行 preload，下一个页面用 preloadData无法读取，使用Taro.getCurrentInstance().preloadData才能拿到数据

**Comment by innocces** [comment]
> > 该方法是针对下一个页面的预加载数据、那么应该是在跳转前的页面执行 preload。 然后在跳转后的页面使用 preloadData。因为本质上 preloadData 是在 router 内查看的
> 
> 对的，实际上的使用是我在上一个页面执行 preload，下一个页面用 preloadData无法读取，使用Taro.getCurrentInstance().preloadData才能拿到数据

不好意思最近太忙。理论上 useRouter 拿的就是 CurrentInstance。因为在 taro 内部实际上维护的路由栈是一个 Current[]. 那这个可能确实还是拿不到. 

方便来个 pr 么

**Comment by innocces** [comment]
这个已经修复了。主包有点问题。等发了包再关闭

**Comment by innocces** [comment]
最新版已经解决  #70
