### ISSUE TITLE
feat(actions):  useRequest options  add fetchKey

### ISSUE THREAD

**Issue by dompling** [innocces/taro-hooks#73]
### Description
列表中多个元素调用同一个接口 loading 和 data 的状态维护
### Solution
类似 [ahooks](https://ahooks.gitee.io/zh-CN/hooks/use-request/index) 的 fetchKey，可以实现列表中维护不同元素的 loading

**Comment by innocces** [comment]
你说的功能是 2x 的一个配置。新的版本是 3x 的

**Comment by innocces** [comment]
新的版本感觉可以用 cacheKey 来模拟一下那个行为。因为不同的 cacheKey 使用的 service 是独立的

**Comment by dompling** [comment]
> cacheKey

感谢回复！
请问一下 3.x 版本没有发布吗？

**Comment by innocces** [comment]
> > cacheKey
> 
> 感谢回复！ 请问一下 3.x 版本没有发布吗？

不是的。
1. taro-hooks@1.x 里的 useRequest 对标的是 ahooks@2.x 的. 有 fetchKey
2. taro-hooks@2.x 里的 useRequest 对标的是 ahooks@3.x 的. 无 fetchKey. 有 cacheKey

**Comment by dompling** [comment]
> 2\. cacheKey

好的，谢谢
