### ISSUE TITLE
bug:使用useRouter的时候报错 

### ISSUE THREAD

**Issue by viilon** [innocces/taro-hooks#74]
### 版本

- taro-hooks:2.0.11
- taro:3.6.28
- node:v20.8.0
- OS:mac

### 复现步骤
```vue
<script setup lang="ts">
const [, {back}] = useRouter();
const onClickSubmitHandle = async () => {
   back();
}

</script>
```

### 现有的现象？
如代码所示，使用useRouter时会报错
页面【modules/xxxr/xxx]错误:
Error: module 'modules/customer-order/sub-vendors.js' is not defined, require args is './sub-vendors.js'

上面代码逻辑是我写在分包后的一个子包里，在主包使用的时候没有问题

**Comment by innocces** [comment]
这个应该是 taro 那边的问题。建议去 taro 那边去建个 issue
