### ISSUE TITLE
自定义组件使用useSelectQuery，

### ISSUE THREAD

**Issue by 39Cclound** [innocces/taro-hooks#9]
### Question
自定义组件使用useSelectQuery，getBoundingClientRect值为空

### Sample Code
![image](https://user-images.githubusercontent.com/52224810/135193683-f45698fd-0591-4d2f-9aa6-6396d265349b.png)

**Comment by innocces** [comment]
目前未提供scope的选项。自定义组件会有这个问题。晚点会修复

**Comment by innocces** [comment]
https://github.com/innocces/taro-hooks/commit/35b8ab72b580688292bdb33d06dc6d3530f1844f#diff-1083555087636ff44e820323f61a23dc89fcb471884f068071c36bc9ad55576eL53

**Comment by innocces** [comment]
最新版已支持`scope`
